# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/mouseDisplay/Nexys4DDR_C.xdc

# IP: ip/Square_Root/Square_Root.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Square_Root || ORIG_REF_NAME==Square_Root}]
