# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: P:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: p:/Private/CMPEN 371/Final Project/lvl_maker/lvl_maker.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
